export const jumblyLines = [
  'VkVjNWVWcFhNR2RoV0VKNlpGY3daMXBIT1hOaU0wbG5ZekpzTUVsSFJuUmFXRkZ6U1VkT2RtSnVUbXhaTTFKc1pFaFdlVWxIUm10aFdFSndZekpPY0dKdFkyZGFW',
  'WkVNMFoxSklWbkJqZVVJeVlWaFNhRnBUUW14amJUbDZTVWMxYkZsNVFteGlSMnd3U1VkR2MyRllSakZhV0ZGbldUSTVkVm96Vm14TWFVSlNaRmRzZW1OWVZteEpS',
  'Mnd3U1VkR2MyRllSakZhV0ZGbldUSTVkVm96Vm14TWFVSlNaRmRzZW1OWVZteEpSMnd3U1VkR2MyRllSakZhV0ZGbldUSTVkVm96Vm14TWFVSlNaRmRzZW1OWVZt',
  'eEpSMnd3U1VkR2MyRllSakZhV0ZGbldUSTVkVm96Vm14TWFVSlNaRmRzZW1OWVZteEpSMnd3U1VkR2MyRllSakZhV0ZGbldUSTVkVm96Vm14TWFVSlNaRmRzZW1O',
  'WVZteEpSMnd3U1VkR2MyRllSakZhV0ZGbldUSTVkVm96Vm14TWFVSlNaRmRzZW1OWVZteEpSMnd3U1VkR2MyRllSakZhV0ZGbldUSTVkVm96Vm14TWFVSlNaRmRz',
  'ZW1OWVZteEpSMnd3U1VkR2MyRllSakZhV0ZGbldUSTVkVm96Vm14TWFVSlNaRmRzZW1OWVZteEpSMnd3U1VkR2MyRllSakZhV0ZGbldUSTVkVm96Vm14TWFVSlNa',
  'RmRzZW1OWVZteEpSMnd3U1VkR2MyRllSakZhV0ZGbldUSTVkVm96Vm14TWFVSlNaRmRzZW1OWVZteEpSMnd3U1VkR2MyRllSakZhV0ZGbldUSTVkVm96Vm14TWFV',
  'SlNaRmRzZW1OWVZteEpSMnd3U1VkR2MyRllSakZhV0ZGbldUSTVkVm96Vm14TWFVSlNaRmRzZW1OWVZteEpSMnd3U1VkR2MyRllSakZhV0ZGbldUSTVkVm96Vm14',
  'TWFVSlNaRmRzZW1OWVZteEpSMnd3U1VkR2MyRllSakZhV0ZGbldUSTVkVm96Vm14TWFVSlNaRmRzZW1OWVZteEpSMnd3U1VkR2MyRllSakZhV0ZGbldUSTVkVm96',
  'Vm14TWFVSlNaRmRzZW1OWVZteEpSMnd3U1VkR2MyRllSakZhV0ZGbldUSTVkVm96Vm14TWFVSlNaRmRzZW1OWVZteEpSMnd3U1VkR2MyRllSakZhV0ZGbldUSTVk',
  'Vm96Vm14TWFVSlNaRmRzZW1OWVZteEpSMnd3U1VkR2MyRllSakZhV0ZGbldUSTVkVm96Vm14TWFVSlNaRmRzZW1OWVZteEpSMnd3U1VkR2MyRllSakZhV0ZGbldU',
  'STVkVm96Vm14TWFVSlNaRmRzZW1OWVZteEpSMnd3U1VkR2MyRllSakZhV0ZGbldUSTVkVm96Vm14TWFVSlNaRmRzZW1OWVZteEpSMnd3U1VkR2MyRllSakZhV0ZG',
  'bldUSTVkVm96Vm14TWFVSlNaRmRzZW1OWVZteEpSMnd3U1VkR2MyRllSakZhV0ZGbldUSTVkVm96Vm14TWFVSlNaRmRzZW1OWVZteEpSMnd3U1VkR2MyRllSakZh',
  'V0ZGbldUSTVkVm96Vm14TWFVSlNaRmRzZW1OWVZteEpSMnd3U1VkR2MyRllSakZhV0ZGbldUSTVkVm96Vm14TWFVSlNaRmRzZW1OWVZteEpSMnd3U1VkR2MyRllS',
  'akZhV0ZGbldUSTVkVm96Vm14TWFVSlNaRmRzZW1OWVZteEpSMnd3U1VkR2MyRllSakZhV0ZGbldUSTVkVm96Vm14TWFVSlNaRmRzZW1OWVZteEpSMnd3U1VkR2My',
  'RllSakZhV0ZGbldUSTVkVm96Vm14TWFVSlNaRmRzZW1OWVZteEpSMnd3U1VkR2MyRllSakZhV0ZGbldUSTVkVm96Vm14TWFVSlNaRmRzZW1OWVZteEpSMnd3U1Vk',
  'R2MyRllSakZhV0ZGbldUSTVkVm96Vm14TWFVSlNaRmRzZW1OWVZteEpSMnd3U1VkR2MyRllSakZhV0ZGbldUSTVkVm96Vm14TWFVSlNaRmRzZW1OWVZteEpSMnd3',
  'U1VkR2MyRllSakZhV0ZGbldUSTVkVm96Vm14TWFVSlNaRmRzZW1OWVZteEpSMnd3U1VkR2MyRllSakZhV0ZGbldUSTVkVm96Vm14TWFVSlNaRmRzZW1OWVZteEpS',
];

export const rollCredits = [
  'Hacking 1st-3rd Level Security',
  'loading',
  'Downloading operator files',
  'loading',
  'Obtaining operative names',
  'loading',
  "Grandma's Secret Recipe",
  'loading',
  'Making Cookies',
  'loading',
  'Beaming Player',
  'loading',
  "location of CODE NAME: Rabbit's Foot",
  'loading',
  "Santa's Workshop Coordinates",
  'loading',
  'WiFi Password',
  'loading',
  'JFK Assasination',
  'loading',
  'Downloading Covid-19 Vaccine',
  'loading',
  'Nordstroms Cupon Codes',
  'loading',
  'Minecraft',
  'loading',
  "The Artist Flower's New Album",
  'loading',
  'Unlocking Back Door',
  'loading',
  'Opening Back Door',
  'loading',
  "Closing Back Door, So We Don't Let The Secrets Out",
  'CONGRATULATIONS!',
  'USERNAME',
  'You have completed game one: Daffodil362',
  'GAMEPLAY TIME',
  'CREDITS:',
  'Story & Puzzle Design: Jonathon McClendon',
  'Coding Team:',
  'Jonathon McClendon',
  'Jonathon McClendon',
  '&',
  'Dylan Dupasquier',
  'Assistant Writer: John McClendon',
  'Play Testers:',
  'John McClendon',
  'Dylan Dupasquier',
  'Gretchen McClendon',
  'Jay Dallen',
  'Aaron Rickles',
  'Scott Rickles',
  'Special Thanks to:',
  '~ Gretchen McClendon (mom)',
  'Sorry for all the computers I ruined in my youth',
  'Trying to take them apart and figure out how they worked.',
  '~ Johnson Family',
  '~ Rickeles Family',
  '~ Bradley & The Tompkins Family',
  'Thank you for the guidance and knowledge you provided me.',
];
